project:
  type: website
  output-dir: docs
  
website:
  title: "Sarah's Work"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects  # line ensures Projects page = linked in navbar
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/sewoolf/website-template
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Sarah Woolf"

format:
  html:
    theme: cerulean
    toc: true

editor: source

